version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: algoliasearch
    versions:
    - ">= 4.a, < 5"
  - dependency-name: webpack
    versions:
    - 5.24.0
    - 5.24.1
    - 5.26.0
    - 5.26.1
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: "@sentry/browser"
    versions:
    - 6.3.0
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 30.0.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.2.2
  - dependency-name: npm
    versions:
    - 7.5.2
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
  - dependency-name: karma
    versions:
    - 6.0.4
    - 6.3.0
  - dependency-name: i18next
    versions:
    - 20.0.0
  - dependency-name: amplitude-js
    versions:
    - 8.0.0
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.2.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
  - dependency-name: "@types/react-select"
    versions:
    - 4.0.12
  - dependency-name: react-select
    versions:
    - 4.2.0
  - dependency-name: google-protobuf
    versions:
    - 3.15.4
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: node
    versions:
    - 15.11.0
    - 15.12.0
    - 15.13.0
    - 15.7.0
    - 15.8.0
    - 15.9.0
