version: 2
jobs:
  build:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true

      - run:
          name: Check that package.json is sorted.
          command: jq . package.json -S | diff - package.json

      - run:
          name: Check that the Dockerfile builds properly.
          command: docker build .

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update
