version: 2.1
jobs:
  check-dependant-repo:  # defines a parameterized job
    description: A job that checks that updated libs don't break the builds based on this image.
    parameters:
      owner:
        description: "Github owner of the target repo"
        default: "bayesimpact"
        type: string
      repo:
        description: "Github name of the target repo"
        type: string
      job-name:
        description: "The name of the CircleCI job to run"
        default: "test-for-base-change"
        type: string
    machine: true
    steps:
      - checkout
      - run: .circleci/test_other_repo.sh "<< parameters.owner >>/<< parameters.repo >>" "<< parameters.job-name >>"
  build:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - setup_remote_docker:
          # Allows to use previous cached version of the built Docker services.
          docker_layer_caching: true
          # Allows to use Node 14+ docker image.
          version: 19.03.13
      - run:
          name: Check that package.json is sorted.
          command: jq . package.json -S | diff - package.json
      - run:
          name: Check that the Dockerfile builds properly.
          command: DOCKER_BUILDKIT=1 docker build -t bayesimpact/react-base:$(.circleci/tag.sh) .
      - run:
          name: Publish docker image.
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
            docker push "bayesimpact/react-base:$(.circleci/tag.sh)"

workflows:
  version: 2.1
  commit:
    jobs:
      - build
      - check-dependant-repo:
          # TODO(cyrille): Find a way to be able to trigger those manually.
          filters:
            branches:
              only: master
          requires:
            - build
          repo: bob-emploi-internal
      - check-dependant-repo:
          filters:
            branches:
              only: master
          requires:
            - build
          repo: ma-voie-internal
