version: 2
jobs:
  build:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true

      - run:
          name: Check that package.json is sorted.
          command: jq . package.json -S | diff - package.json

      - run:
          name: Check that the Dockerfile builds properly.
          command: docker build -t bayesimpact/react-base:latest .

      - run:
          name: Push to Docker Hub
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]] || [[ "$CIRCLE_BRANCH" == *-test-push ]]; then
              docker build -t "bayesimpact/react-base:$CIRCLE_BRANCH" .
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
              docker push "bayesimpact/react-base:$CIRCLE_BRANCH"
            fi
workflows:
  version: 2
  commit:
    jobs:
      - build
